#line 1 "/home/dmitri/Documents/Work/Coding/App/0_0_Recording_Apps/rec_app/arduino_firmware/arduino_send_interrupt/other/welcome_text.h"
static String welcome_text = "\n\n"
"|   |   | /   \\  /   \\ /    /  /   ]  |  |  | /    ||    \\   /   ]  \n"
"|       ||     ||     (   \\   /  [ |  |  |  ||  o  ||  D  ) /  [      \n"
"|  \\ /  ||  O  ||  O  |\\    ||     ]  |  |  ||     ||    / |     ]   \n"
"|   |   ||     ||     |/  \\ ||   [ |  '  '  ||     ||    \\ |   [     \n"
"|   |   ||     ||     |\\    ||     |\\      / |  |  ||  .  \\|     |  \n"
"|   |   | \\   /  \\   /  \\   ||     | \\ /\\ /  |  |  ||  |\\ ||     |  \n\n"
"MOOSEWARE RPI Pico v0.65\n\n"
"(c) Neureflect Inc. 2023\n"
"by Dmitri Yousef Yengej\n"
"\n"
"CONTROLLER COMMANDS:\n"
"send with: {\"CTRL\": {\"command\": value}} e.g. {\"CTRL\": {\"run\": 1}} to start\n"
"\nCommand:      Values:\n"
"- run:        0: stop rec (idle), 1: start rec\n"
"- freq:       float, target recording freq in Hz\n"
"\n\n"
"all chips can be turned on or off with:\n"
"{\"CHIP SHORTNAME\": {\"record\": 0 or 1}}\n\n"
"other chip instructions are defined in the driver of the chip\n"
"and can be send with:\n"
"{\"CHIP SHORTNAME\":  {\"command\": value}}\n"
"e.g.: {\"OIS\": {\"amps\": 8}} set the led current to 8mA\n" 
"\n\n"
;